# Generated by Django 5.1.7 on 2025-04-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthtip',
            name='image',
        ),
        migrations.AddField(
            model_name='healthtip',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
