# Generated by Django 4.2.19 on 2025-04-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaffeineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkName', models.CharField(max_length=255)),
                ('volumeML', models.IntegerField()),
                ('calorie', models.IntegerField()),
                ('caffeine', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
