# Generated by Django 4.2.19 on 2025-04-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_caffeineproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='caffeineintake',
            name='drink_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caffeineintake',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
