# Generated by Django 4.2.19 on 2025-04-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_caffeineintake_drink_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthtip',
            options={'ordering': ['title']},
        ),
    ]
