# Generated by Django 4.2.19 on 2025-04-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_healthtip_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthtip',
            options={},
        ),
        migrations.AlterField(
            model_name='healthtip',
            name='icon_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='healthtip',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='healthtip',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
