# Generated by Django 5.1.7 on 2025-04-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
