# Generated by Django 5.1.7 on 2025-05-02 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaffeineProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkName', models.CharField(max_length=255)),
                ('volumeML', models.IntegerField()),
                ('calorie', models.IntegerField()),
                ('caffeine', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('status', models.BooleanField()),
                ('flOz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mgPerFlOz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mgPer100ml', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'caffeine_products',
                'ordering': ['drinkName'],
            },
        ),
        migrations.AlterModelOptions(
            name='healthtip',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='caffeineintake',
            name='categoryType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caffeineintake',
            name='drink_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caffeineintake',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='CreatedDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkName', models.CharField(max_length=255)),
                ('volumeML', models.IntegerField(blank=True, null=True)),
                ('caffeine', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mgPer100ml', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('category', models.CharField(max_length=100)),
                ('measurementMethod', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_created', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
