# Generated by Django 4.2.19 on 2025-04-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_healthtip_options_alter_healthtip_icon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caffeineproduct',
            name='flOz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='caffeineproduct',
            name='mgPerFlOz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
