# Generated by Django 5.1.7 on 2025-05-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_caffeineproduct_alter_healthtip_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caffeineintake',
            name='is_created',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
