# Generated by Django 4.2.19 on 2025-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_caffeineproduct_mgper100ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='caffeineintake',
            name='categoryType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
