# Generated by Django 4.2.19 on 2025-04-30 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0008_caffeineintake_categorytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkName', models.CharField(max_length=255)),
                ('volumeML', models.IntegerField(blank=True, null=True)),
                ('caffeine', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mgPer100ml', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
