# Generated by Django 4.2.19 on 2025-04-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_createddrink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createddrink',
            name='mgPer100ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
