# Generated by Django 4.2.19 on 2025-04-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_createddrink_mgper100ml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createddrink',
            name='caffeine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
