# Generated by Django 4.2.19 on 2025-04-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_alter_createddrink_caffeine'),
    ]

    operations = [
        migrations.AddField(
            model_name='createddrink',
            name='measurementMethod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createddrink',
            name='caffeine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createddrink',
            name='drinkName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createddrink',
            name='mgPer100ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createddrink',
            name='volumeML',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
