# Generated by Django 4.2.19 on 2025-04-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_createddrink_measurementmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createddrink',
            name='caffeine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='createddrink',
            name='drinkName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='createddrink',
            name='mgPer100ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='createddrink',
            name='volumeML',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
