# Generated by Django 4.2.19 on 2025-05-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_alter_createddrink_caffeine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createddrink',
            name='is_created',
            field=models.BooleanField(default=True),
        ),
    ]
