# Generated by Django 4.2.19 on 2025-05-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_createddrink_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='caffeineintake',
            name='is_created',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
