# Generated by Django 4.2.19 on 2025-05-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_caffeineintake_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='health_condition',
            field=models.CharField(choices=[('none', 'None'), ('pregnant', 'Pregnant'), ('lactating', 'Lactating'), ('heart', 'Heart Condition'), ('hypertension', 'Hypertension'), ('diabetes', 'Diabetes')], default='none', max_length=20),
        ),
    ]
