# Generated by Django 4.2.19 on 2025-05-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_caffeineintake_is_created'),
        ('monitoring', '0016_userprofile_health_condition'),
    ]

    operations = [
    ]
